spring.application.name=spring-server

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MongoDB Atlas
spring.mongodb.uri=${SPRING_MONGODB_URI:***}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:***}

# JWT Configuration
jwt.secret=${JWT_SECRET:***}
jwt.expiration=${JWT_EXPIRATION:***}

# Python Model Server
python.server.url=${PYTHON_SERVER_URL:***}
python.server.api-key=${PYTHON_SERVER_API_KEY:***}

# CORS Allowed Origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:***}

# Azure Blob Storage
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:***}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:***}