spring.application.name=spring-server

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MongoDB Atlas
spring.mongodb.uri=***
spring.mongodb.database=prenatalvision

# JWT Configuration
jwt.secret=***
jwt.expiration=***

# Python Model Server
python.server.url=http://localhost:5000
python.server.api-key=***

# CORS Allowed Origins
cors.allowed-origins=***

# Azure Blob Storage
azure.storage.connection-string=
azure.storage.container-name=scans